name: tests-ci
run-name: CI - ${{ github.actor }}
on: [push]
jobs:
    build-debug:
        uses: ./.github/workflows/build.yaml
        with:
            build_type: "debug"
        secrets:
            ciip: ${{ secrets.ciip }}
            ciport: ${{ secrets.ciport }}
            cimac: ${{ secrets.cimac }}
    build-release:
        uses: ./.github/workflows/build.yaml
        with:
            build_type: "release"
        secrets:
            ciip: ${{ secrets.ciip }}
            ciport: ${{ secrets.ciport }}
            cimac: ${{ secrets.cimac }}
        needs: build-debug
    build-production:
        uses: ./.github/workflows/build.yaml
        with:
            build_type: "production"
        secrets:
            ciip: ${{ secrets.ciip }}
            ciport: ${{ secrets.ciport }}
            cimac: ${{ secrets.cimac }}
        needs: [build-debug, build-release]

